version: '3'
services:

    api:
      build: ./
      ports:
        - "80:3000"
      command: uvicorn app.main:app --host 0.0.0.0 --port 3000
      volumes:
        - ./app:/api/app
      depends_on:
        - db
      networks:
        - backend


    db:
      image: mongo
      ports:
        - "27017:27017"
      volumes:
        - mongo_data:/data/db
      networks:
        - backend

volumes:
    mongo_data:

networks:
    backend: