version: '3'
services:

    api:
      build: ./
      ports:
        - "3000:3000"
      volumes:
        - ./app:/app

    db:
      image: mongo
      ports:
        - "27017:27017"
      volumes:
        - mongo_data:/data/db

volumes:
    mongo_data: